server:
  port: 10010
spring:
  application:
    name:  api-gateway #指定服务名
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka

zuul:
  routes:
    service-provider: # 这里是路由id，随意写
      path: /service-provider/** # 这里是映射路径
      url: http://127.0.0.1:8081 # 映射路径对应的实际url地址